ble.lwp3.bytecodes: Fix IODeviceCapabilities enum
Fix failing on newer versions of Python which are more strict about
empty enums.

Fixes the following error:

    TypeError: <flag 'IODeviceCapabilities'> has no members; specify `names=()` if you meant to create a new, empty, enum